/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Clases.Clinica;
import Clases.Especialidades;
import Clases.ImagenFondo;
import Clases.Medicos;
import Clases.Pacientes;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;

/**
 *
 * @author
 */
public class Interfaz_Principal extends javax.swing.JFrame {
    private InputStream foto1 = this.getClass().getResourceAsStream("/Imagenes/FondoPrincipal.jpg");

    /**
     * Creates new form Interfaz_Principal
     */
    Clinica cl;
    public Interfaz_Principal() {
        initComponents();
        cl = new Clinica();
         cargarImagen(jDesktopPane1, foto1);
        setExtendedState(MAXIMIZED_BOTH);
    }
    public void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new ImagenFondo(image));
        } catch (Exception e) {
            System.out.println("Imagen no disponible");
        }
    }
    
    public void cargarDatos(){
        //Especialidades
        cl.insertarEspecialidad(new Especialidades("S1Obs", "Obstetricia"));
        cl.insertarEspecialidad(new Especialidades("S2Ped", "Pediatria"));
        cl.insertarEspecialidad(new Especialidades("S3MG", "Medicina General"));
        cl.insertarEspecialidad(new Especialidades("S4Ped", "Cardiologia"));
        
        //Medicos
        Especialidades e = cl.buscarEspecialidad("S1Obs");
        e.insertarMedico(new Medicos("1234567890", "Jose", "Peña", 'H', e.getCodigo()));
        e.insertarMedico(new Medicos("0123456789", "Maria", "Lascano", 'M', e.getCodigo()));
        
        Especialidades e1 = cl.buscarEspecialidad("S2Ped");
        e1.insertarMedico(new Medicos("1236548745", "Josefina", "Duran", 'M', e1.getCodigo()));
        e1.insertarMedico(new Medicos("0123456798", "Josefa", "Jaramillo", 'M', e1.getCodigo()));
        
        Especialidades e2 = cl.buscarEspecialidad("S3MG");
        e2.insertarMedico(new Medicos("1236548743", "Pedro", "Calle", 'H', e2.getCodigo()));
        e2.insertarMedico(new Medicos("0123456788", "Francisco", "Tomalo", 'H', e2.getCodigo()));
        
        Especialidades e3 = cl.buscarEspecialidad("S4Ped");
        e3.insertarMedico(new Medicos("12365487452", "Melanie", "Gallardo", 'M', e3.getCodigo()));
        e3.insertarMedico(new Medicos("0123456758", "Mishelle", "Gallo", 'M', e3.getCodigo()));
        
        //Pacientes
        cl.insertarPaciente(new Pacientes("0258741369", "Marco", "Carranza", 'H', "Ambato"));
        cl.insertarPaciente(new Pacientes("0369852147", "Sonia", "Esquivel", 'M', "Ambato"));
        cl.insertarPaciente(new Pacientes("0147852369", "Mishelle", "Paz", 'M', "Ambato"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jmbOpciones = new javax.swing.JMenuBar();
        especialidades = new javax.swing.JMenu();
        medicos = new javax.swing.JMenu();
        pacientes = new javax.swing.JMenu();
        citas = new javax.swing.JMenu();
        cargar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        individual = new javax.swing.JMenuItem();
        mensual = new javax.swing.JMenuItem();
        especialidad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        especialidades.setText("Especialidades");
        especialidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                especialidadesMouseClicked(evt);
            }
        });
        especialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadesActionPerformed(evt);
            }
        });
        jmbOpciones.add(especialidades);

        medicos.setText("Médicos");
        medicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicosMouseClicked(evt);
            }
        });
        jmbOpciones.add(medicos);

        pacientes.setText("Pacientes");
        pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacientesMouseClicked(evt);
            }
        });
        jmbOpciones.add(pacientes);

        citas.setText("Citas Medicas");
        citas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                citasMouseClicked(evt);
            }
        });
        jmbOpciones.add(citas);

        cargar.setText("Cargar Datos");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cargar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        cargar.add(jMenuItem1);

        jmbOpciones.add(cargar);

        Reportes.setText("Reportes");

        individual.setText("Reporte por Individual");
        individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individualActionPerformed(evt);
            }
        });
        Reportes.add(individual);

        mensual.setText("Reporte Mensual");
        mensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensualActionPerformed(evt);
            }
        });
        Reportes.add(mensual);

        especialidad.setText("Reporte por Especialidad");
        especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadActionPerformed(evt);
            }
        });
        Reportes.add(especialidad);

        jmbOpciones.add(Reportes);

        setJMenuBar(jmbOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cargarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:cargarDatos();
        cargarDatos();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void especialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadesActionPerformed

    private void especialidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_especialidadesMouseClicked
        // TODO add your handling code here:
        Interfaz_Especialidades iesp = new Interfaz_Especialidades(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_especialidadesMouseClicked

    private void medicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicosMouseClicked
        // TODO add your handling code here:
        Interfaz_Medicos iesp = new Interfaz_Medicos(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_medicosMouseClicked

    private void pacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientesMouseClicked
        // TODO add your handling code here:
        Interfaz_Pacientes iesp = new Interfaz_Pacientes(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_pacientesMouseClicked

    private void citasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citasMouseClicked
        // TODO add your handling code here:
        Interfaz_Citas_Medicas iesp = new Interfaz_Citas_Medicas(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_citasMouseClicked

    private void individualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualActionPerformed
        // TODO add your handling code here:
        Interfaz_Reporte_Individual iesp = new Interfaz_Reporte_Individual(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_individualActionPerformed

    private void mensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensualActionPerformed
        // TODO add your handling code here:
        Interfaz_Reporte_Mensual iesp = new Interfaz_Reporte_Mensual(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_mensualActionPerformed

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
        // TODO add your handling code here:
        Interfaz_Reporte_Especialidad iesp = new Interfaz_Reporte_Especialidad(cl);
        jDesktopPane1.add(iesp);
        iesp.setLocation(jDesktopPane1.getWidth() / 2 - iesp.getWidth() / 2, jDesktopPane1.getHeight() / 2 - iesp.getHeight() / 2);    
        iesp.show();
    }//GEN-LAST:event_especialidadActionPerformed

    public void mos(){
        System.out.println(cl.espcLista.nElementos);
        System.out.println(cl.pacLista.nElementos);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenu cargar;
    private javax.swing.JMenu citas;
    private javax.swing.JMenuItem especialidad;
    private javax.swing.JMenu especialidades;
    private javax.swing.JMenuItem individual;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar jmbOpciones;
    private javax.swing.JMenu medicos;
    private javax.swing.JMenuItem mensual;
    private javax.swing.JMenu pacientes;
    // End of variables declaration//GEN-END:variables
}
